### ISSUE TITLE
CreateTable<> Fails

### ISSUE THREAD

**Issue by shawnburge** [oysteinkrog/SQLite.Net-PCL#106]
Howdy!

I am trying to use these libraries in a couple of projects and I am getting an error when I attempt to execute CreateTable<>.

Exception:
SQLite.Net.SQLiteException : near ")": syntax error
   at SQLite.Net.Platform.Win32.SQLiteApiWin32.Prepare2(IDbHandle db, String query)
   at SQLite.Net.SQLiteCommand.Prepare()
   at SQLite.Net.SQLiteCommand.ExecuteNonQuery()
   at SQLite.Net.SQLiteConnection.Execute(String query, Object[] args)
   at SQLite.Net.SQLiteConnection.CreateTable(Type ty, CreateFlags createFlags)
   at SQLite.Net.SQLiteConnection.CreateTable(CreateFlags createFlags)
   at SqliteDataProvider.ResetDatabase() in SqliteDataProvider.cs: line 25
   at SqliteTests.DatabaseTests.BuildDatabase() in DatabaseTests.cs: line 13

Code Snippets:
internal class Answers {
	[PrimaryKey, AutoIncrement]
	internal int AnswerId { get; set; }
	internal int QuestionId { get; set; }
	[MaxLength(512)]
	internal string AnswerText { get; set; }
	internal bool IsCorrect { get; set; }
}

using (SQLiteConnection connection = _sqlite.GetConnection()) {
	connection.CreateTable<Answers>();
	connection.Close();
}

Any ideas?

Thanks!!
Shawn

**Comment by oysteinkrog** [comment]
Hi, thanks for the report.
I think this is an error in your code though.
SQLite.net uses reflection to see the properties in your class/tables, which means that marking the properties internal will not work, they must be public.

**Comment by shawnburge** [comment]
Øystein,

I thought about that right after I submitted this, and that did resolve the issue.

Thanks!! :-)
